# vim:ft=kitty

## name:     Catppuccin-Mocha
## author:   Pocco81 (https://github.com/Pocco81)
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!


    #01161f
    #022533
    #13465b
    #205e77
    #327f9f
    #3a8fb2        
    #46a5cd
    #4eb3dd
    #54c0ed        
    #8cd6f5
    #a7e0f8
    #c7ebfa        
    #db2360
    #f182b5
    #ffc3ef        
    #f04933
    #f49b53        
    #f0616a
    #ffd971
    #e3fc9e        
    #45997d
    #72bb98
    #98d9af
    #b9f2c2


# The basic colors
foreground              #8cd6f5
background              #01161f
selection_foreground    #01161f
selection_background    #c7ebfa

# Cursor colors
cursor                  #c7ebfa
cursor_text_color       #01161f

# URL underline color when hovering with mouse
url_color               #c7ebfa

# Kitty window border colors
active_border_color     #B4BEFE
inactive_border_color   #6C7086
bell_border_color       #F9E2AF

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #11111B
active_tab_background   #CBA6F7
inactive_tab_foreground #8cd6f5
inactive_tab_background #181825
tab_bar_background      #11111B

# Colors for marks (marked text in the terminal)
mark1_foreground #01161f
mark1_background #B4BEFE
mark2_foreground #01161f
mark2_background #CBA6F7
mark3_foreground #01161f
mark3_background #74C7EC

# The 16 terminal colors

# black
color0 #45475A
color8 #585B70

# red
color1 #db2360
color9 #f182b5

# green
color2  #d4ef87
color10 #e3fc9e

# yellow
color3  #ffd971
color11 #edcd88

# blue
color4  #4eb3dd
color12 #8cd6f5

# magenta
color5  #f0616a
color13 #d87980

# cyan
color6  #72bb98
color14 #98d9af

# white
color7  #BAC2DE
color15 #A6ADC8
